### ISSUE TITLE
Window not responding

### ISSUE THREAD

**Issue by calebwin** [emoon/rust_minifb#100]
I tried the `noise` example by building from source. Unfortunately, it takes up 30-35% of CPU usage and the window immediately is not responding. This happens as soon as I (and even if I only) invoke `Window::new`.

I have a Dell Inspiron laptop with Intel i7 16gb, Windows 10, Intel GPU.

Is this expected? I'm trying to use this for [stdg](https://github.com/calebwin/stdg) but if the window doesn't respond I can't.

**Comment by emoon** [comment]
That sounds strange. Have you tried to just do something like this

```
 while window.is_open() && !window.is_key_down(Key::Escape) {
        window.get_keys().map(|keys| {
            for t in keys {
                match t {
                    Key::W => println!("holding w!"),
                    Key::T => println!("holding t!"),
                    _ => (),
                }
            }
        });

        window.update_with_buffer(&buffer).unwrap();
    }
```

And see how that works? Also regarding CPU time. The code currently will try to run as fast as it can. It can be a good idea to limit the frame rate (add sleeping) so it doesn't try to consume all the CPU time.

**Comment by calebwin** [comment]
Hi @emoon. Sorry for not closing this earlier.

This isn't actually an issue at all with MiniFB at all. The problem was that I was not calling `window.update_with_buffer(&buffer).unwrap();` as often as possible in an infinite loop, which seems to be necessary. Everything seems to be working smoothly now that I do that.

Thank you for creating this library, btw. I'm finding it very useful at the moment.

**Comment by emoon** [comment]
Cool. np :)
