### ISSUE TITLE
Wrong curser on resizeable window

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#109]
If window is set to resizable `true` on first entering the window the mouse cursor is shown as resize cursor on the whole window.  This occurs on Window 10.

https://gitlab.redox-os.org/redox-os/orbtk/issues/210

**Comment by emoon** [comment]
Tentative fix in https://github.com/emoon/rust_minifb/commit/daa57e9fa9e71c6639b0b04e8789c89a4db84032 (need to get my windows machine running for a proper check)

**Comment by FloVanGH** [comment]
Ok cool.

**Comment by maroider** [comment]
It seems to have fixed the issue where the cursor would show as the loading wheel.
The other issue mentioned may or may not have been fixed. Dragging the cursor in from the left, right or bottom sides of the window will cause the cursor to stay as one of the resizing cursors.

https://gitlab.redox-os.org/redox-os/orbtk-mirror/issues/206

**Comment by emoon** [comment]
I have fixed this issue in the `dev` branch now
