### ISSUE TITLE
Rewrite Linux/X11 version in Rust

### ISSUE THREAD

**Issue by emoon** [emoon/rust_minifb#11]

**Comment by andwj** [comment]
Hello,

I have ported the X11 version to Rust.  The code is on Gitlab.
You can import the branch into the main repository, so you can have a look
and (I hope) merge it, using the following command:

```
git fetch https://gitlab.com/andwj/minifb-x11.git +x11-rs:x11-rs
```

An outstanding issue is that the DisplayInfo struct, which is used to communicate
with the X server, is not shared, and this means that only a single window can be
used at a time.  The event handling code also cannot handle multiple windows.

**Comment by emoon** [comment]
Sweet! Do you think it would be possible to fix the multiple window handling before I get this?

**Comment by andwj** [comment]
I was not sure the best way to handle the opened X display, which in my code is
stored in a DisplayInfo struct, and needs to be shared between all windows.

There seems to be two main choices: using a "static mut" variable, or using the
lazy_static crate.  The latter would be an extra dependency.  Seeing much of the
code is unsafe anyway, the "static mut" variable doesn't seem as bad as it normally
would, though wrapping DisplayInfo in an Option<> may get a bit paiful.

What do you think?  Did you have a particular plan in mind for that?

**Comment by emoon** [comment]
I haven't thought much about this. I know multiple windows works on Mac and Windows and I know some people are using them so having the Linux support there as well would be great :)

**Comment by andwj** [comment]
Ok, I will experiment with using lazy_static and see how it goes.

**Comment by ZanderBrown** [comment]
@andwj any progress?

**Comment by andwj** [comment]
Unfortunately not, and I have stopped using Rust and don't plan to pick it up again.

**Comment by ZanderBrown** [comment]
Sad to hear that, hope we didn't scare you off!

**Comment by FauxFaux** [comment]
I rebased this branch on master, leaving only the scale factor selection a mess:
https://github.com/FauxFaux/rust_minifb/tree/andwj

I plan to look at cleaning that up, and looking at the `DisplayInfo` TODO at some point, unless anyone has had any ideas?
