### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by nifker** [emoon/rust_minifb#114]
I get about 40% CPU usage(CPU is an Intel i5-4300M), reported from top. On both Wayland and X11.
For a simple example as follwing:

```
//imports...

fn main(){
  let mut Window::new("Test", 640, 400, WindowOptions::default()).unwrap();
  while window.is_open(){
    window.update();
    //even when adding std::thread::sleep(std::time::Duration::from_nanos(1));
    //it doesnt matter
  }
}
```

**Comment by emoon** [comment]
This code will do a lot of system calls (which is done inside the update) what you want to do is to limit how many "fps" your application can run in. For example if you want your application to run at 60 fps you the whole loop should take 16.6 ms. So what you can do is have something like this (pseudo code) 

```Rust
while window.is_open() {
   let current_time = time::SystemNow();
   // your update code here
   ...
   window.update();
   let duration = time::SystemNow().duration(start_time);
   if duration < 16.6 {
    thread::sleep(16.6 - duration);
  }
}

**Comment by nifker** [comment]
But wouldn't this slow down the input responsiveness? As I found out the utilization is also high on higher systems.
Your first approach didn't fix it - only when sleeping 1ms at the end I still have about 10% CPU usage(which I think is still high for an application doing nothing).

**Comment by emoon** [comment]
Games that runs at 60 fps does something similar and there input responsiveness is quite important. if you want even faster you could limit to sleep about 8 ms in total time and that response rate is quite high. 

> Your first approach didn't fix it

This should cause your application to sleep like 15 ms. Did you verify that this is the case?

Also if you look at the code here https://github.com/emoon/rust_minifb/blob/master/src/os/unix/mod.rs#L449 it doesn't actually do much code

It calls this 

https://github.com/emoon/rust_minifb/blob/master/src/key_handler.rs#L53
https://github.com/emoon/rust_minifb/blob/master/src/os/unix/mod.rs#L691

and this

https://github.com/emoon/rust_minifb/blob/master/src/os/unix/mod.rs#L719

Except the first call (which is just a few lines of code) almost all the time is spent in calling `X11` system functions.

I have notice that these system calls can be slow but I have to do them to get the correct key events and mouse location.

**Comment by nifker** [comment]
Seems to be somewhat better now. But wouldn't it be more efficient to use an Iterator for all events?

**Comment by emoon** [comment]
If you mean this code https://github.com/emoon/rust_minifb/blob/master/src/os/unix/mod.rs#L722 then almost all of the time will spent calling the X11 functions so I doubt it will make much difference.

**Comment by emoon** [comment]
I have added some functionality for this in the `dev` branch. If it would be possible for you to try that out and then do something like this

```Rust
    // Limit to max ~60 fps update rate
    window.limit_update_rate(Some(std::time::Duration::from_micros(16600)));
```

Before the update loop

**Comment by nifker** [comment]
Ill definitely try this(later or tomorrow).

**Comment by emoon** [comment]
thanks!

**Comment by nifker** [comment]
This already seems to work pretty good - only about 1% per core, even when updating with an image.
(Could be even less on X11)

**Comment by emoon** [comment]
Great! I will close this one then when I release the new version
