### ISSUE TITLE
Noise example shows no noise when initially run (Windows 10)

### ISSUE THREAD

**Issue by maroider** [emoon/rust_minifb#116]
The noise only appears after I've resized the window a bit. Smaller sizes seem to more reliably produce the intended result. Even when the noise appears, the bottom half of the frame often flickers quickly between noise and black. At other times, the bottom half is completely black.
A "quick" `git bisect` shows that 2b8094cc6ce7fefeb322a8b4df09e0c978efd5e2 introduced the issue.

**Comment by emoon** [comment]
Thanks for the report. I will take a look at it.

**Comment by emoon** [comment]
Hi, I wonder if you are able to test again with the `dev` branch of minifb? I have made a bunch of fixes in there.

**Comment by maroider** [comment]
It seems like it's fine now.
