### ISSUE TITLE
Resizing a window can make it display unexpected things (Windows 10)

### ISSUE THREAD

**Issue by maroider** [emoon/rust_minifb#117]
There are three main issues that I've encountered:
1. Making the window really small and "massaging" it by continuously resizing it will eventually cause it to display parts of the desktop. I've been able to reproduce this intermittently with the noise example, but I've also observed this issue when resizing a window made through orbtk (which uses minifb internally).
2. By running the noise example and the orbtk-based window mentioned above and then "massaging" the orbtk window, I'm able to observe the noise from the noise example in the orbtk-based window.
3. Performing the "massaging" procedure on the orbtk-based window will sometimes cause the framebuffer to be displayed multiple times. This may also be happening with the noise example but that is difficult to be certain of.

I ran both the noise example and the orbtk-based window with f181e2d67ce2602834ee52a0e7b1a8327beaac47.

**Comment by emoon** [comment]
Thanks. I will take a look at it.

**Comment by emoon** [comment]
Hi, I wonder if you are able to test again with the `dev` branch of minifb? I have made a bunch of fixes in there.

**Comment by maroider** [comment]
It looks like it's fixed now.
