### ISSUE TITLE
Ubuntu touch support

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#121]
The first mobile OS we will support with Orbtk is Ubuntu Touch https://ubuntu-touch.io/. Ubuntu Touch Apps are based on Qt and there is a official way to implement apps for Ubuntu with Rust and Qt. I think the easiest way to support Ubuntu Touch in minifb and OrbTk is to wrap a QtWindow. Would you agree with it? 

With the support of mobile OS it would be also necessary to add support for touch gestures.

I'd be willing to implement that ;-)

**Comment by emoon** [comment]
Yes I'm just a bit curious of how it would work as minifb has it's own message loop to handling incoming events and such while Qt is based on signals/slots system.

Mobile support in general would be cool and I will for sure accept PR regarding that :)

**Comment by FloVanGH** [comment]
Ok nice :-). I think I have an idea how I could implement it.

**Comment by emoon** [comment]
I read that you are switching away from minifb for Orbtk, so I wonder if you still plan to implement this or should I close it?

**Comment by FloVanGH** [comment]
Yes you can close it. At the moment we are using OrbClient as default window backend and minifb as backup. 

I have some alternatives in mind that maybe work directly on Ubuntu touch. Otherwise I will implement Ubuntu Touch support directly one OrbTk or in OrbClient.

**Comment by emoon** [comment]
Sounds good. Thanks!
