### ISSUE TITLE
Set ns_view on raw_window_handle

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#130]
Is it possible to set ns_view to raw_window_handle on macos? I need it to use wgpu https://github.com/gfx-rs/wgpu-rs with minifb.

**Comment by emoon** [comment]
Yeah it should be possible. It just needs to be passed out from the ObjC code. I don't have much time this week to look at it but I can try

**Comment by FloVanGH** [comment]
Ok thank you.

**Comment by emoon** [comment]
This has been implemented in 0.15.3 Sorry for the delay!
