### ISSUE TITLE
Debug message logged in release builds too

### ISSUE THREAD

**Issue by legends2k** [emoon/rust_minifb#136]
When running an executable built with `cargo build --release` I still see these message

> 2020-01-23 17:15:32.240832+0530 mandelbrot[73453:488530] Names (null)
> 2020-01-23 17:15:32.279533+0530 mandelbrot[73453:488530] MessageTracer: Falling back to default whitelist

These are perhaps OK in debug build but is there a reason these're needed in release build as well?

**Comment by emoon** [comment]
I fixed the first one now. The second one is a bit weird because it isn't minifb that prints that so it's likely coming from the OS for some reason.

**Comment by emoon** [comment]
Tested this with the latest version and macOS 13.0 and it seems there is no such message anymore so closing this issue
