### ISSUE TITLE
Borderless window macOS / Linux

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#145]
Set borderless to `true` on `WindowOptions` does not work on macOS and Linux (tested with X11).

**Comment by valkum** [comment]
https://github.com/emoon/rust_minifb/blob/882e7bc7add440fa7a9062b08673ba7a21fbfd38/src/native/macosx/MacMiniFB.m#L179-L188

I think in the case of a borderless window we do not want a close button.
So the flags are not correct here.
Also the docs say something about `canBecomeKeyWindow`/`canBecomeMainWindow` are these set in the case of `borderless: true`?

https://developer.apple.com/documentation/appkit/nswindowstylemask?language=objc

**Comment by FloVanGH** [comment]
@valkum Set `borderless: true`and `tille: false` works. Thank you.
