### ISSUE TITLE
Keys seem to be pressed twice

### ISSUE THREAD

**Issue by VeridianDynamics** [emoon/rust_minifb#153]
Here's a minimalistic application to reproduce the issue:
```rust
extern crate minifb;

use minifb::{Key, Window, WindowOptions};
use std::{thread, time};
use std::time::{SystemTime, UNIX_EPOCH};

const WIDTH: usize = 640;
const HEIGHT: usize = 360;

fn main() {
	let ten_millis = time::Duration::from_millis(10);
		let mut blackbuf: Vec<u32> = vec![0; WIDTH * HEIGHT];
	
	for i in blackbuf.iter_mut() {
		*i = 0;
	}
	let mut colorbuf: Vec<u32> = vec![0; WIDTH * HEIGHT];
	for i in colorbuf.iter_mut() {
		*i = 200;
	}

	let mut window = Window::new(
		"Test - ESC to exit",
		WIDTH,
		HEIGHT,
		WindowOptions::default(),
	)
	.unwrap_or_else(|e| {
		panic!("{}", e);
	});

	// Limit to max ~60 fps update rate
	window.limit_update_rate(Some(std::time::Duration::from_micros(16600)));

	let mut press_counter: u32 = 0;
	while window.is_open() && !window.is_key_down(Key::Escape) {
		if window.is_key_released(Key::Space) {
				println!("Space released");
		}
		let mut sleep_time = ten_millis;
		if window.is_key_down(Key::Space) {
			let start = SystemTime::now();
    		let since_the_epoch = start.duration_since(UNIX_EPOCH)
        		.expect("Time went backwards");
			let in_ms = since_the_epoch.as_secs() * 1000 + since_the_epoch.subsec_nanos() as u64 / 1_000_000;
			println!("Space pressed at {}", in_ms);
			window.update_with_buffer(&colorbuf, WIDTH, HEIGHT).unwrap();
			sleep_time = time::Duration::from_millis(1000);
			println!("Press counter is {}", press_counter);
			press_counter += 1;
		} else {
			window.update_with_buffer(&blackbuf, WIDTH, HEIGHT).unwrap();
		}
		thread::sleep(sleep_time);

	}
}
```
Here's an example output:

> Space pressed at 1585425664033
> Press counter is 0
> Space pressed at 1585425665042
> Press counter is 1
> Space released
> Space pressed at 1585425666912
> Press counter is 2
> Space pressed at 1585425667919
> Press counter is 3
> Space released

So it seems that the key is pressed twice and only released once. This is my first Rust project, so I might be doing something wrong, but the only parts I'm uncertain about is the unwrap() call and thread::sleep.

**Comment by trevarj** [comment]
Increase the `sleep_time`?

**Comment by VeridianDynamics** [comment]
It already sleeps for a whole second, yet the key is registered again after it wakes up. I also figured it might have something to do with the key repeat interval, but that has a reasonable default, so it's not that either. I was able to sort of hack around it by calling `window.update()` without parameters before and after the sleep.

I also noticed that sometimes when I press spacebar it doesn't register the keypress but does register the release action.

**Comment by trevarj** [comment]
What if you use `is_key_pressed()` instead of `is_key_down()` and pass it `KeyRepeat::No`?

**Comment by emoon** [comment]
Yes, you should use `is_key_pressed` and use `KeyRepeat::No`

**Comment by emoon** [comment]
Closing this issue now. If you still have problems please open it again.
