### ISSUE TITLE
Possibly remove some Debugging information : NSLog(@"Names %@", [g_library functionNames]);

### ISSUE THREAD

**Issue by phillvancejr** [emoon/rust_minifb#155]
In src/native/macosx/MacMiniFB.m there is this function on line 117:
NSLog(@"Names %@", [g_library functionNames]); 

I've been using Orbtk which depenends on this library, and every time an app is compiled on MacOS we get a line on the console like 2020-03-31 07:24:22.389 minimal[3070:58936] Names (null).  Is this Log useful for anything currently? If not it would be nice to remove it, just so that only necessary things are logged to the console

**Comment by emoon** [comment]
no, it's fine to remove it. If possible open a PR for the change.

**Comment by emoon** [comment]
Fixed in PR https://github.com/emoon/rust_minifb/pull/156
