### ISSUE TITLE
x11-dl not found

### ISSUE THREAD

**Issue by violetasuwu** [emoon/rust_minifb#160]
Hello, when I try and compile my project that uses minifb, I get the following errors (most of them are the same with minor variations but I decided it's best to include them):
https://gist.github.com/JacobSinclair/9f4ea6ec51692d6478e188fef5018ad7

**Comment by JacobSinclair** [comment]
Ah I think I see the issue, in minifb's `Cargo.toml` it doesn't include anything for `musl` targets on linux (I use the musl libc)

**Comment by JacobSinclair** [comment]
#161

**Comment by JacobSinclair** [comment]
nevermind, it seems that Rust doesn;t support any sort of dynamic linking on musl at all

**Comment by emoon** [comment]
I see. I don't think there is anything I can do about it then.

**Comment by emoon** [comment]
Closing this. Please re-open if you have some idea how to sort it out
