### ISSUE TITLE
Make cursor invisible

### ISSUE THREAD

**Issue by nifker** [emoon/rust_minifb#166]
It might be nice to be able to make the cursor invisible(only within the application), so that applications can draw their own bitmaps as cursor onto the surface.

**Comment by nifker** [comment]
I would propose an implementation if this is of interest.

**Comment by nifker** [comment]
I would have this ready - I am just missing an OSX implementation I can neither test nor cross-compile this currently. Is there someone who can implement this(on my branch)?

**Comment by nifker** [comment]
@emoon Why is the osx implementation written in objective C and not using bindings(like the X11 impl does)?

**Comment by emoon** [comment]
1. There are/were no similar bindings for the macOS APIs when I implemented it.
2. I tried to use the creates for `objc!(...)` calls but I was unable to get it working.

**Comment by emoon** [comment]
Implemented in https://github.com/emoon/rust_minifb/pull/170
