### ISSUE TITLE
Could Window be marked Send

### ISSUE THREAD

**Issue by adamreichold** [emoon/rust_minifb#176]
`Window` is currently not `Send` which severely limits how it can be used in a multi-threaded environment. Is this limitation necessary due to the underlying OS-specific implementations or could this guarantee be given?

(For example, it seems that `minifb::os::unix::x11::Window` contains a `*mut x11::xlib::XImage` and hence just needs to be explicitly marked `Send`. Or does this pointer or the data contained in the `XImage` instance reference stack-local data after all?)

**Comment by emoon** [comment]
I know before I switched to Metal on macOS those API calls had to be done on the main-thread but right now I'm not sure. One would have to look at all the implementations to verify that they can be called in a safe fashion show then.

Right now I would recommend having worker threads that generates the data you want and then have one thread (main) that gets that data to be used for presentation.

**Comment by adamreichold** [comment]
> One would have to look at all the implementations to verify that they can be called in a safe fashion show then.

Since `Send` is a build time guarantee, could this just be different between different platforms? I.e. `Window` is `Send` on Windows and Unix but not for macOS or would you consider this too much of a portability hazard?

**Comment by emoon** [comment]
I really want minifb to work the same on all platforms as this is what I as a user would expect on any library.

**Comment by adamreichold** [comment]
Understood, let's close this then.

**Comment by emoon** [comment]
It would be nice to have this implemented but needs research on all platforms. Right now I currently have the time to do so but if anyone want to look into it that would be great.
