### ISSUE TITLE
Linux is not Unix

### ISSUE THREAD

**Issue by LoganDark** [emoon/rust_minifb#195]
It's a semi-common convention to call systems that could be either Unix or Linux "*nix systems". BSD is a type of Unix, but Linux is its own thing.

When you use `unix`, you seem to mean both Linux and BSD (which are both *nix systems), but I think it could be more correct to say `nix` instead. Or perhaps `posix`. Many *nix OSes aren't strictly POSIX compliant (macOS is), but almost all of them are POSIX-like. `posix` is the more technical one, while `nix` is more informal.

Honestly, I would go for `posix` for build systems and the like but either one would work. And both are better than saying that Linux is Unix! :P

**Comment by emoon** [comment]
If you want to make a PR with a suggested change I would be willing to accept it if it look ok, otherwise I feel there are way more important things to fix and spend time on.

**Comment by LoganDark** [comment]
> otherwise I feel there are way more important things to fix and spend time on.

Yeah I had the new issue page open for like 24 hours and even closed the tab once before deciding to post this. I'll see if I can make a PR.

**Comment by LoganDark** [comment]
`nix` or `posix`?

**Comment by emoon** [comment]
Hum.. hard one. I think both works really but `nix` perhaps because macOS is `posix` compliant?

**Comment by emoon** [comment]
Also if you do the PR there are some `Unix` in the docs (and also the `unix` namespace)

**Comment by LoganDark** [comment]
Well, you do already use `unix` even though macOS is Unix, so using `posix` even though macOS is POSIX-compliant wouldn't be much different. Also don't you use some of the unix things for macOS anyway?

**Comment by emoon** [comment]
Well if you look here https://github.com/emoon/rust_minifb/tree/master/src/os You can see that `macos` is it's own backend. That is because macOS is mainly implemented in ObjC because objC is kinda annoying to use from Rust. Also macOS supports menus and such while X11 doesn't have such concept. In minifb x11 (and wayland) is mainly for "unix"

**Comment by LoganDark** [comment]
> You can see that macos is it's own backend.

Yeah, I can see that. Why `nix` over `posix`? I'll admit, I'm a bit biased since I came up with `posix` after some thought and it seems better suited for this purpose.

**Comment by emoon** [comment]
Like I said, `posix` is fine also so go with that if you feel that is better.
