### ISSUE TITLE
Switch app in task bar will got hang on win7

### ISSUE THREAD

**Issue by lynnux** [emoon/rust_minifb#196]
It's strange when switch app between minifb and other gui app on taskbar, the taskbar will hang some times.
I modified the code to test, and find solution, change https://github.com/emoon/rust_minifb/blob/master/src/os/windows/mod.rs#L770
```
while winuser::PeekMessageW(&mut msg, window, 0, 0, winuser::PM_REMOVE) != 0 {
```
to 
```
while winuser::PeekMessageW(&mut msg, std::ptr::null_mut(), 0, 0, winuser::PM_REMOVE) != 0 {
```

**Comment by emoon** [comment]
```
A handle to the window whose messages are to be retrieved. The window must belong to the current thread.

If hWnd is NULL, PeekMessage retrieves messages for any window that belongs to the current thread, and any messages on the current thread's message queue whose hwnd value is NULL (see the MSG structure). Therefore if hWnd is NULL, both window messages and thread messages are processed.

**Comment by lynnux** [comment]
I simply tested the multi window, it seems ok, also tested `multi_window` example from orbtk-develop, also seems good.
The `PeekMessageW` with `DispatchMessageW` seems only dispatch MSG to wnd_proc, no matter how many loops are there. If set wnd to NULL, PeekMessageW will got other window's msg, it's should be fine, the wnd_proc will properly handle it.
I don't know if some one else encounter the same problem, it seems no issured before.

**Comment by emoon** [comment]
Alright. I will give it a spin and see how it works

**Comment by emoon** [comment]
Seems to work good. I have changed the code now. If you want to try it directly you can use the gitversion instead in your `Cargo.toml` but I will try to release a new version later today.

**Comment by emoon** [comment]
0.17 has been released with this fix. Thanks!
