### ISSUE TITLE
Consider rewriting in a threaded fashion

### ISSUE THREAD

**Issue by emoon** [emoon/rust_minifb#21]
As noted in #15 right now the main thread gets stuck when polling for events (this happens for example if a user holds a menu key down the whole it gets stuck inside the event loop updating but doesn't call to the outside ever)

It might be possible to keep the way the API looks today intact but unsure yet. Other benefits is that when running with `update_with_buffer` a copy of the buffer can be made and then the window thread can actually update this while the main thread keeps running.

Of course with threading comes it's own sets of issues. Should it be possible to set update frequency of the window thread (so it doesn't hammer to much or should one just do the "classic" way of sleeping 1 ms?)

**Comment by jedahan** [comment]
I am not sure this is related, but I am having trouble creating a window inside a rust thread. Here is a minimal example: https://github.com/jedahan/rust_minifb_threaded/blob/master/src/main.rs . If this is more a question for #rust or #rust-beginners, feel free to ignore.

**Comment by emoon** [comment]
The way your code works is that the main thread will exit directly after the ``println(...)`` call. You need to join with your thread that creates the UI. That being said minifb hasn't really been tested at all for multi-threading so there might be some other issues also.

**Comment by emoon** [comment]
Ok so your code works on Linux but not on Mac. Maybe there is some code that needs to be executed on the main thread or Mac or so (like some of the init functions)

**Comment by jedahan** [comment]
Woah! That is promising news. I will see if I can use gdb or some other debugging to learn more. I tried creating the main window outside the thread and moving it in, but Send is not automatically derived. I'll try splitting up the ::new a bit more to track down the issue.

**Comment by emoon** [comment]
Thanks! Yeah I guess one could try to implement it as "dummy" send and say that it's safe to move it over. One would have to consult the Cocoa docs and see if it's legal to move a window created on one thread over to another because it might not be.

I'm primary thinking of the code inside here: https://github.com/emoon/rust_minifb/blob/master/src/native/macosx/MacMiniFB.m#L58

Maybe some of that needs to be on main thread before the window creation. I would try that but that is mostly speculation because I haven't actually looked at it yet.

**Comment by jedahan** [comment]
Seems to be on OSX some GUI operations are thread unsafe, and some must be on the main thread:

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html#//apple_ref/doc/uid/10000057i-CH12-123351-BBCFIIEB

With some workarounds maybe in https://users.rust-lang.org/t/guis-and-the-main-thread/2863/8

**Comment by emoon** [comment]
I see. One way I guess would be to leave minifb on main thread and have the other code in a separate thread.

**Comment by jedahan** [comment]
Here is a minimal working example of shared memory, with the cpu being the child thread. I am absolutely ecstatic to get this far with minifb. https://github.com/jedahan/rust_minifb_threaded/blob/master/src/main.rs . If you'd like, I can clean it up a bit and submit it as an example program to the main repo for others, adding some comments on why we got here.

**Comment by emoon** [comment]
Thanks!

One thing to think about though

```Rust
fn foo() {
  let frame = *self.frame.read().unwrap();
  // frame is now locked for the full function!
}
```

In this code https://doc.rust-lang.org/std/sync/struct.RwLock.html#examples you can see that the code is being wrapped in such way with a scope that the lock with not be held for so long.

Another way to do this would be to use channels instead if wanted. https://doc.rust-lang.org/std/sync/mpsc/

I'm happy to include it in main repro with some clean up and maybe give channels a go and see if that would work good also (I haven't given it that much thought but should work)

**Comment by emoon** [comment]
Will close this one as I don't think it's worth doing. Better would be to move more backends of to use GPU (as the macOS one) as it would make the time spent in the update very small
