### ISSUE TITLE
Remove debug printing in Windows impl

### ISSUE THREAD

**Issue by yupferris** [emoon/rust_minifb#218]
It seems there are a few `println`'s left over:

https://github.com/emoon/rust_minifb/blob/15bce84a4edfb99a79490cc1598abc583a988461/src/os/windows/mod.rs#L938

I assume this is by mistake - should we remove these?

**Comment by emoon** [comment]
doh! yes :)

**Comment by emoon** [comment]
I will fix

**Comment by emoon** [comment]
Fixed in 0.19.1

**Comment by yupferris** [comment]
ha, that was fast, cheers!
