### ISSUE TITLE
On Windows, buffers larger than the window cause weird artifacts and look horrible

### ISSUE THREAD

**Issue by LoganDark** [emoon/rust_minifb#221]
At least on Windows, displaying a buffer larger than the size of the window causes weird artifacts.

My ray tracer is a good example of this, and is how the bug was discovered.

At 1x resolution:

![image](https://user-images.githubusercontent.com/4723091/95449127-2f759700-0919-11eb-8a94-1f899a5723b7.png)

At 2x resolution:

![image](https://user-images.githubusercontent.com/4723091/95448640-83cc4700-0918-11eb-9739-4011070385aa.png)

My friends with real Windows machines originally reported this bug to me, then I confirmed that it also happens in Wine, so I think the problem is minifb.

**Comment by LoganDark** [comment]
Here are some gifs

Bug:

![raytracerbugwindows](https://user-images.githubusercontent.com/4723091/95450359-0950f680-091b-11eb-9d95-3d0142736fe0.gif)

Not bug:

![raytracernotbugwindows](https://user-images.githubusercontent.com/4723091/95450548-4d43fb80-091b-11eb-886f-2832e41d1b2e.gif)

The _only_ difference is the resolution of the framebuffer - no color calculation is affected by resolution in my code, in fact nothing is except for the amount of rays that are put out.

**Comment by emoon** [comment]
Exactly how do you send this larger than window buffer to minifb?

**Comment by LoganDark** [comment]
@emoon by using `update_with_buffer` ... ???

It's exactly the same as sending a buffer that's the same size as the window, or smaller than the window.

**Comment by emoon** [comment]
ok, I will have to investigate it. You can workaround the issue by scaling it manual (which you may or may not want to do anyway if you want super-sampled downscaling) minifb on will only scale with nearest filtering.

**Comment by LoganDark** [comment]
And you can make it unnecessary for adding a function for me to query DPI scaling (since I only multiply the resolution by 2 to support high DPI on macOS -_-)

**Comment by emoon** [comment]
temporary you can always check if you are running on macOS or Windows.

**Comment by LoganDark** [comment]
🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮

**Comment by emoon** [comment]
Hey, I wrote temporary above.

**Comment by LoganDark** [comment]
I'd rather wait for a fix is what I mean lol

**Comment by emoon** [comment]
Also, if you are in such hurry you can add it yourself.

**Comment by LoganDark** [comment]
Sorry, I did not mean to imply that I was in any sort of hurry, but you're not being very helpful by telling me to go do it myself.

**Comment by emoon** [comment]
I said if you want super-sampled down scaling (i.e anti-aliasing) you would have to do yourself (as minifb doesn't support it) regular scaling should work, but I don't think I have tested with buffer larger than the screen

**Comment by emoon** [comment]
I can try to get `dpi_scale` function added during the weekend.

**Comment by LoganDark** [comment]
Oh, you're misunderstanding me then. I'm taking advantage of the extra pixels on macOS, not trying to do antialiasing. However somehow that causes minifb on Windows to flip out when the display _doesn't_ have those extra pixels.

**Comment by emoon** [comment]
Fair enough, yeah that is how I pretty much interpret it as well. Understood. I will get the scaling added soonish.

**Comment by emoon** [comment]
won't get around to implement it this weekend

**Comment by LoganDark** [comment]
Any progress on that `dpi_scale` function?

**Comment by emoon** [comment]
Sorry, not yet

**Comment by emoon** [comment]
Just FYI I have started to work on this but it's quite a lot of work.

**Comment by emoon** [comment]
Being tracked in #236
