### ISSUE TITLE
MacOS displays blurry lines

### ISSUE THREAD

**Issue by curlywurlycraig** [emoon/rust_minifb#226]
# Description

With a retina display Macbook (Mojave, mid-2014, 13"), it is as if retina is not being used.

With the following code:

```rust
use minifb::{Key, Window, WindowOptions};

const WINDOW_WIDTH: usize = 200;
const WINDOW_HEIGHT: usize = 100;

fn main() {
    let mut window = Window::new(
        "Example window",
        WINDOW_WIDTH,
        WINDOW_HEIGHT,
        WindowOptions::default()
    ).unwrap_or_else(|e| {
        panic!("{}", e);
    });

    // Limit to max ~60 fps update rate
    window.limit_update_rate(Some(std::time::Duration::from_micros(16600)));

    let mut buffer: Vec<u32> = vec![0; WINDOW_WIDTH * WINDOW_HEIGHT];

    while window.is_open() && !window.is_key_down(Key::Escape) {
        // Alternate between white and black
        for i in buffer.iter_mut().enumerate() {
            *i.1 = if i.0 % 2 == 0 { 0xFFFFFF } else { 0x00 }
        }

        window
            .update_with_buffer(&buffer, WINDOW_WIDTH, WINDOW_HEIGHT)
            .unwrap();
    }
}
```

I see the following result:

<img width="312" alt="Screenshot 2020-12-02 at 11 14 42" src="https://user-images.githubusercontent.com/5550263/100865737-a6e62380-348f-11eb-888c-f23c04dcd062.png">

when I would expect the lines to be 1 pixel wide every time.

I wonder if this is related to changing to use Metal.

**Comment by curlywurlycraig** [comment]
Hang on, I just noticed that if I zoom into that window, the screenshot is showing 1 pixel for each line 🤔

**Comment by curlywurlycraig** [comment]
Ah yes. It appears to be two pixels wide, not one. As if what we actually need is a 0.5X scaling factor. I still suspect this is related to the change to using Metal.

**Comment by emoon** [comment]
If you set WindowOpts to something like

```Rust
  WindowOptions {
            scale: Scale::X2,
            ..WindowOptions::default()
        },
```

Does it seem to look better?

**Comment by curlywurlycraig** [comment]
That makes it worse (4 pixels for every real pixel): 

<img width="512" alt="Screenshot 2020-12-02 at 13 22 48" src="https://user-images.githubusercontent.com/5550263/100878022-87f08d00-34a1-11eb-89e9-b5861fc9a783.png">

**Comment by emoon** [comment]
Ok, doubling of pixels is expected (that is the point of the scale factor) but not sure about the need for 0.5X scale and I doubt it's related to Metal. I just thing it's because minifb doesn't do anything special for HiDPI. It would be interesting to know if it looks correct if you set macOS to non-scaled mode.

**Comment by curlywurlycraig** [comment]
The problem remains when I use default for display. If this isn't related to Metal, is it possibly something in the Cocoa window management code? I don't know much about Cocoa unfortunately, so I can only get so far trying to debug this myself.

**Comment by emoon** [comment]
I see. I will have to look into it at some point, but currently I don't have easy access to my mac so I can't do it for a while.

**Comment by curlywurlycraig** [comment]
Sure. Thanks for your help

**Comment by LoganDark** [comment]
All you have to do is multiple the width and height by two. This is intended behavior and minifb is working correctly.

**Comment by curlywurlycraig** [comment]
Makes sense, thanks.

**Comment by emoon** [comment]
Being tracked in #236
