### ISSUE TITLE
Request: more flexible InputCallback mechanism?

### ISSUE THREAD

**Issue by floooh** [emoon/rust_minifb#24]
The only way to get char codes seems to be through the InputCallback, but since this consumes a Box<InputCallback> I'm having trouble getting the data "out" of the callback since the Box<> is moved away into the depths of minifb :) The examples I've seen (in examples/menu.rs, and in ProDBG) both don't make the data available up to the caller (menu.rs just has a println!(), and ProDBG calls a 'global' imgui wrapper function).

Is there a recommended way to make the char code data available up in the main loop? I'm still a Rust noob, and I'm not sure what a good solution would be. The simplest would probably be to collect all char codes for a frame and make them available through polling, similar to get_keys()? The most important functionality for me is to get the UNICODE char code (as opposed to virtual key codes), whether through polling, a callback closure or callback trait isn't important to me :)

**Comment by emoon** [comment]
I will look at it.

I can't remember why I decided to make it callback based because everything else isn't so there must be some reason behind it.

**Comment by kondrak** [comment]
We talked about it at the time and the reason to do it this way is to maintain simplicity. One idea was to use an event pump in a similar fashion SDL does but it was decided that for a minimalistic crate like this it's an overkill. At least when I was working on Rust64, the only way to fetch the data was to poll each key individually or fetch a state array of currently pressed keys. The latter, however, was painfully slow (note that I was using Rust 1.5 then, so it might have been a compiler issue which is now resolved).

**Comment by floooh** [comment]
Thanks! Please take your time, I'm not blocked by this :) I would provide a pull request but don't feel proficient in Rust enough yet for this to be useful.

I'm currently mapping key codes back to ASCII, it kinda works, but is hardwired to American-English keyboard layout. Having the char-codes available would automatically make it work for international keyboard layout (at least if they can produce the ASCII codes used by most 8-bit home computers).

**Comment by emoon** [comment]
Example of how to handle this has been added here https://github.com/emoon/rust_minifb/blob/master/examples/char_callback.rs
