### ISSUE TITLE
Incorrect size of non-decorated windows on Windows

### ISSUE THREAD

**Issue by swismer** [emoon/rust_minifb#245]
When creating a non-decorated window on Windows, the size of the window is too large, because the calculation always assumes decoration. This issue is not obvious as the oversize area seems to be transparent. Clicking on it reveals the issue.
I tracked it down to Window.open_window(): https://github.com/emoon/rust_minifb/blob/e5b5cc50d581494c38612c7dd835609d18e08eff/src/os/windows/mod.rs#L510-L514
Here different window flags are used to determine the size compared to when creating the window (line 552). According to https://stackoverflow.com/a/25879124 the same flags should be used for both WinAPI calls.

**Comment by emoon** [comment]
Fixed by https://github.com/emoon/rust_minifb/pull/246
