### ISSUE TITLE
'Plonk sound' on keyboard input in macOS 10.12 Sierra Beta

### ISSUE THREAD

**Issue by floooh** [emoon/rust_minifb#25]
I just noticed when turning up the sound on OSX 10.12, a 'key plonk' sound is played when a key is pressed in a minifb window (as if the the window isn't accepting keyboard input). It's the same sound that plays when you look at a text file with 'less', and try to scroll past the end when hitting the Space key, or when you go to "About this Mac" in the Apple menu, and try Cut/Copy/Paste in the about-window.

This reproduces in the minifb examples (e.g. the noise example), just run the sample and start pressing keys.

I don't know whether this also happens on older OSX versions. The complete version number of the 10.12 Beta is "10.12 Beta (16A254g)".

**Comment by emoon** [comment]
Found the issue. I will fix some more that I have pilled up and release a new version tonight/tomorrow :)

**Comment by floooh** [comment]
Thanks a lot!

**Comment by emoon** [comment]
Lets keep this one open until I submitted a fix :)

**Comment by emoon** [comment]
Alright. Try 0.8.3 and it should be fixed

**Comment by floooh** [comment]
Confirmed working. Thanks :)
