### ISSUE TITLE
Question: Why does KeyHandler::get_keys() return an Option?

### ISSUE THREAD

**Issue by Zij-IT** [emoon/rust_minifb#259]
Hello there! I just started using minifb, and was looking at the source for `KeyHandler::get_keys` when I noticed that it returned a `Option<Vec<Key>>`, but I didn’t see a case in which it would ever return `None`.

I am curious what the reasoning behind that is. To me it seems like returning just a `Vec<Keys>` would suffice, as if no keys are pressed, the `Vec` is empy. 

Thanks for your time!

**Comment by beyarkay** [comment]
Can this issue be closed?
