### ISSUE TITLE
get_scroll_wheel should give you the current scroll position instead of last delta.

### ISSUE THREAD

**Issue by NikoUY** [emoon/rust_minifb#264]
I'm not sure how it works on other platforms but on MacOS you only get the delta, it's pretty useless without a way to get notified when someone uses the scroll wheel or a way to check for changes.

You can add the deltas to the current position [here](https://github.com/emoon/rust_minifb/blob/75a25ce898102392ee24c0cdd69b724412b08ffb/src/native/macosx/OSXWindowFrameView.m#L389), that way you can check if the value changed.

**Comment by emoon** [comment]
The idea is that the application can determine what the current position is as this can be application specific. You can implement it something like this

```Rust
   ...
   let mut scroll_pos = (0, 0);
   while window.open(...) {
      window.get_scroll_wheel().map(|scroll| {
        // user has now moved the scroll wheel/trackpad
        scroll_pos += scroll;
      });
   }
```

**Comment by NikoUY** [comment]
How would I know when the user stopped scrolling?, the value never resets to 0 and it's a constant depending on the direction and the speed of the scroll wheel (1 is slow and 4 is fast), I could check if the value changed but since it never resets to 0 I would only be able to know if the user changed direction but I won't be able to tell if the user scrolled more than once on the same direction or if the user stopped scrolling.

**Comment by emoon** [comment]
I see. I have only tested this with trackpad where it works correct, I will have to check how it differs with mouse wheel.

**Comment by emoon** [comment]
So the problem seems to be that the callback code for mouse wheel gets called all the time since the first time the user has done scrolling even when no scrolling is active. Not really sure why that is the case

**Comment by emoon** [comment]
Seems to be a `macOS` only problem. Works correct on Linux and Windows

**Comment by emoon** [comment]
I think I have found the problem. Looking into a fix

**Comment by emoon** [comment]
I have pushed a fix now. Give the git version a try and see if it solves your issue. If it does I will release a new version

**Comment by NikoUY** [comment]
Yep, that works! 😄, thanks for fixing it!

**Comment by emoon** [comment]
Great! Thanks for the report. I will release a new version in a bit :)

**Comment by emoon** [comment]
Version 0.20 has now been released with this fix
