### ISSUE TITLE
Expose window scale or mouse position scaled?

### ISSUE THREAD

**Issue by jedahan** [emoon/rust_minifb#27]
Hey, I was wondering if you'd be open to exposing the window scale and/or a scaled version of get_mouse_pos that would show what 'non-scaled' pixel the mouse was over.

**Comment by emoon** [comment]
Sure. I can add both

**Comment by emoon** [comment]
Added ``get_unscaled_mouse_pos`` Hopefully that will do the trick for you.

**Comment by jedahan** [comment]
wonderful support emoon, thanks for everything!

**Comment by emoon** [comment]
np :)
