### ISSUE TITLE
get_mouse_down returns true even after releasing the mouse button from outside the window and coming back in without pressing

### ISSUE THREAD

**Issue by arnabanimesh** [emoon/rust_minifb#280]
Let's say I click inside the window and start dragging. In the meantime, the cursor goes outside the window and the mouse button is released. If I bring back the cursor once again inside the window, the library thinks that the button is still pressed even though it has been released.

OS: Windows 11 x64

**Comment by emoon** [comment]
Thanks for the report. I will try to take a look at it today.
