### ISSUE TITLE
Need to do a status bar at the bottom of the frame buffer to show dynamic text content

### ISSUE THREAD

**Issue by arnabanimesh** [emoon/rust_minifb#282]
Maybe I want to show the frames per second or some details about the graphics I am showing which is updated frame by frame. The look will be like the menu bar

**Comment by emoon** [comment]
I'm not sure what you are asking for. You can just render your own text at the bottom of the screen?

**Comment by emoon** [comment]
No, it's not. It would be a Windows only feature and I try to stick with multi-platform as much as possible, so it's out scope currently.
