### ISSUE TITLE
ctrl-modifier does not work (main, mac-os)

### ISSUE THREAD

**Issue by tinkerlog** [emoon/rust_minifb#289]
Hi there,
it looks as if the ctrl-modifier does not work on main branch on Mac-OS.
Also I don't see
* Enter
* Backspace
* Tab
working.

The command-modifier doesn't seem to work as well, it gives the same key as un-modified.
Cheers!

**Comment by emoon** [comment]
Hey,

I added this code

```
        if window.is_key_down(Key::Enter) {
            println!("Enter is down");
        }

        if window.is_key_down(Key::Tab) {
            println!("Tab is down");
        }

        if window.is_key_down(Key::Backspace) {
            println!("Backspace is down");
        }
 ```
 
 In the `noise.rs` example code and ran it on macOS and this works fine for me.

**Comment by tinkerlog** [comment]
Wow, thanks for the quick response!
Works fine!
I expected somehow to see the keys in the char_callback example.
Haven't looked closely at the other examples, sorry.

**Comment by emoon** [comment]
In general I would recommend using the "regular" `key_is_down/released/etc` functions instead of the `char_callback` The callback is mainly there if you need to deal with specific Unicode characters and such.

**Comment by tinkerlog** [comment]
Will do, thanks!
