### ISSUE TITLE
Menus do not Work on macOS Before Reselecting Window

### ISSUE THREAD

**Issue by thisjaiden** [emoon/rust_minifb#334]
# Issue
When running `cargo run --example menu` or writing code that uses menu functionality, menus do not work until the window is deselected and re-selected. Specifically, menus show up but clicking on them does nothing. This includes both the 🍎 menu, about menu, and any user menus.

# Environment
- Hardware: M2 Macbook Air, 24GB RAM, 2022 model
- OS: macOS 13.3.1a
- rustc 1.77.0-nightly (190f4c961 or 2024/01/09)
- I have also tried the latest stable rust (1.75.0)
- cargo 1.77.0-nightly (2ce45605d or 2024/01/04)
- `rust_minifb = "0.25.0"`
- I have also tried the master branch

# Things I have Found
[This StackOverflow post](https://stackoverflow.com/questions/73416679/application-main-nsmenu-not-responding-without-window-reactivation) seems to describe this issue (though not for this library or even Rust) and suggests that it's the underlying `NSApp`/`AppKit` not getting fully initialized.

I have a little experience with Rust and macOS FFIs, but looking at how this library and `rust-windowing/raw-window-handle` manage making an `NSWindow` I have *no clue* how the `NSApp` context is created, managed, ect. If all of that is implied by some higher level shortcut in the FFI, then it may be a macOS bug. If it's not, it may be a bug with this library or any of its dependencies. I was unsuccessful in digging any further.

I'm happy to help with any hardware testing needed, and taking it to any dependencies' projects. If some indication of exactly where this initialization happens is pointed to I may be able to make a PR.

Thanks much for the great crate! :)

**Comment by emoon** [comment]
Hi,

Thanks :)

Thanks for the report. The macOS backend is actually not implemented in Rust but in ObjC (of course there is a layer to talk with Rust) but all setup is here https://github.com/emoon/rust_minifb/tree/master/src/native/macosx

If you would be willing to have a look at this code in order to do a PR that would be awesome!

**Comment by thisjaiden** [comment]
Made a [quick PR](#335), thankfully just a two line change. Thanks for the pointer!

**Comment by emoon** [comment]
fixed by #335
