### ISSUE TITLE
Memory Leak on macOS?

### ISSUE THREAD

**Issue by St3Ko** [emoon/rust_minifb#34]
is it possible, that there is a memory leak on macOS? I'm running El Capitan and the example code on the front-page which just creates an empty (black) buffer seems to gain slowly but constantly memory.

Used code:

```
extern crate minifb;

use minifb::{Window, Key, Scale, WindowOptions};

const WIDTH: usize = 640;
const HEIGHT: usize = 360;

fn main() {
    let mut buffer: Vec<u32> = vec![0; WIDTH * HEIGHT];

    let mut window = Window::new("Test - ESC to exit",
                                 WIDTH,
                                 HEIGHT,
                                 WindowOptions::default()).unwrap_or_else(|e| {
        panic!("{}", e);
    });

    while window.is_open() && !window.is_key_down(Key::Escape) {
        for i in buffer.iter_mut() {
            *i = 0; // write something more funny here!
        }

        window.update_with_buffer(&buffer);
    }
}
```

![1](https://cloud.githubusercontent.com/assets/11004885/22856592/abb22370-f094-11e6-8cc6-9888da4c9b27.png)

![2](https://cloud.githubusercontent.com/assets/11004885/22856594/afadd47e-f094-11e6-84dc-d192dc124e57.png)

![3](https://cloud.githubusercontent.com/assets/11004885/22856595/b288eac6-f094-11e6-8eca-0a0307b4c80b.png)

after approx. 30 sec of running

**Comment by emoon** [comment]
Interesting. I will take a look at it. Thanks for the report!

**Comment by emoon** [comment]
With the upgrade to Metal this should be no issue anymore. Please re-open if you see this again.
