### ISSUE TITLE
X11 Dep Issue on Elementary OS

### ISSUE THREAD

**Issue by DaveKram** [emoon/rust_minifb#36]
Here's a log of running cargo build:

> david@davids-laptop:~/devwork/gbaemulator$ cargo build
   Compiling libc v0.1.12
   Compiling libc v0.2.23
   Compiling gcc v0.3.50
   Compiling dylib v0.0.1
   Compiling time v0.1.37
   Compiling x11-dl v2.2.1
   Compiling minifb v0.9.1
error: failed to run custom build command for minifb v0.9.1
process didn't exit successfully: 
/home/david/devwork/gbaemulator/target/debug/build/minifb-dd163c76d6efa2a1/build-script-build (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/home/david/devwork/gbaemulator/target/debug/build/minifb-c081ab0c3ee253cf/out/src/native/x11/X11MiniFB.o" "-c" "src/native/x11/X11MiniFB.c"
cargo:warning=src/native/x11/X11MiniFB.c:1:27: fatal error: X11/Xresource.h: No such file or directory
cargo:warning=compilation terminated.
exit code: 1
command did not execute successfully, got: exit code: 1
--- stderr
thread 'main' panicked at 'explicit panic', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.50/src/lib.rs:1210
note: Run with RUST_BACKTRACE=1 for a backtrace.
Build failed, waiting for other jobs to finish...
error: build failed

Pretty sure I installed X11 via apt-get as well. This is just a dependency in my Cargo.toml - works well on my Win10 machine.

**Comment by emoon** [comment]
I think you need to install the x11-devel package or such.

I have Travis building for Linux over here https://travis-ci.org/emoon/rust_minifb/jobs/225092831 and it seems to work fine.

**Comment by DaveKram** [comment]
Ahhh, it's a 
`apt-get install xorg-dev`
which finally installed all the necessary things.

Thanks!

**Comment by emoon** [comment]
Great that it works now. np!
