### ISSUE TITLE
Resize doesn't actually work (for me?) on macOS

### ISSUE THREAD

**Issue by elanini** [emoon/rust_minifb#38]
Upon resizing the window, the content still stays the same size and has a gray border on the top and right, and the resized buf does not draw correctly.

I had to add this:
```diff
diff --git a/orig.m b/OSXWindowFrameView.m
index 9e7a5bc..850aba7 100644
--- a/OSXWindowFrameView.m
+++ b/OSXWindowFrameView.m
@@ -132,9 +132,14 @@ - (void)windowResized:(NSNotification *)notification;
     if (window->shared_data) {
         window->shared_data->width = (int)(size.width);
         window->shared_data->height = (int)(size.height);
+        window->draw_buffer = malloc((int)size.width*(int)size.height*4);
+        draw_buffer = window->draw_buffer;
+        window->width = (int)size.width;
+        window->height = (int)size.height;
+        width = (int)size.width;
+        height = (int)size.height;
     }
 }
 
 @end
```

However I'm sure there's a better way to fix it so I don't really want to submit that as a pull request.

**Comment by emoon** [comment]
Thanks! I will look into it.

**Comment by jedahan** [comment]
Let me know if you want some additional macOS testing.

**Comment by emoon** [comment]
Thanks. I run macOS as my primary OS so I should be able to proper testing if needed :)

**Comment by emoon** [comment]
I have rewritten the macOS backend so resize should work correctly now. Please re-open if you have issues with it
