### ISSUE TITLE
Window::get_size() inconsistent on Windows

### ISSUE THREAD

**Issue by yupferris** [emoon/rust_minifb#42]
Using the latest published version (0.10.1) on Windows, with `WindowOptions::resize = true`, `get_size` initially returns the size of the client area of the window. However, after resizing the window, `get_size` will return the total size of the window (including title bar, border, etc). I believe the correct semantic is to always return the client size, as this is most useful when creating a pixel buffer to draw to within this area.

**Comment by emoon** [comment]
Makes sense. I will try to look into this during the weekend.

**Comment by yupferris** [comment]
Hmm, I just dug into this a tiny bit and tested on my work machine, and not only does WM_SIZE give client area size (which is what's being used on Windows), but it appears to work correctly.. perhaps I did something wrong and opened this prematurely :) . I'll look into it further on my end as well one of these evenings.

**Comment by emoon** [comment]
Alright :)

**Comment by yupferris** [comment]
Ok, sorry for the noise, not sure what I did wrong here initially, but it does indeed appear to work as expected. At least we got some additional eyes on the code, hehe :)

**Comment by emoon** [comment]
Ok cool :)
