### ISSUE TITLE
Support drag'n'drop of files

### ISSUE THREAD

**Issue by emoon** [emoon/rust_minifb#44]
This has been requested now and then and would be nice to support. The way it would work is that the program can call a `get_files_dropped` function or something similar that returns `Option<Vec<Path>>` I think that would be good enough for many use-cases.

**Comment by francesca64** [comment]
Is there any reason winit can't be used for windowing? It would give you these features (along with others), and reduce your maintenance burden.

**Comment by emoon** [comment]
I would gain some and lose some. For example I don't think winit supports menus. This crate started out to be much simpler and has grown more than I wanted it to really wanted it to but I will consider it.

**Comment by francesca64** [comment]
> I don't think winit supports menus

This is true. Menus are still an unresolved bit of API design in winit, and I'm also not confident that they're within winit's scope (that's not to say that I'm averse to adding them, but that enough thought hasn't gone into it yet).

Anyway, if there's anything you need, just let me know and I can probably implement it (I'm winit's maintainer, hence the evangelism).

**Comment by emoon** [comment]
Thanks! I will consider it for sure :)
