### ISSUE TITLE
fullscreen windows

### ISSUE THREAD

**Issue by aeosynth** [emoon/rust_minifb#50]
Hi, I'd like to make windows fullscreen, thanks. I suppose currently I could manually get the screen size and set the image to that.

**Comment by emoon** [comment]
Hi, Currently there is no support for fullscreen no.

**Comment by SuperCuber** [comment]
Is there anything specific preventing it currently?

**Comment by emoon** [comment]
It depends a bit on how you want to implement it. There are two ways I see doing it

1. Switch the resolution of the monitor. This is what games do, and yields better performance.
2. Scale the screen to fit the current screen resolution.

Both of the above requires correct aspect ratio handling for the screen to look correct. Also it the style of window needs to be changed as well (so no title is shown etc)

So while there is nothing really preventing it it's a bunch of work to support on all platforms as the APIs for each platform is different and currently macOS, Linux, Windows and Redox is supported.

**Comment by emoon** [comment]
Yes but because minifb just renderes one fullscreen quad pretty much all GPUs can do that at full speed for your desktop resolution. So instead of actually changing the desktop resolution it would render a `borderless maximized` window at the current desktop res.

**Comment by nifker** [comment]
@emoon AFAIK Fullscreen mode is used to prevent compositing and thus reduce latency.
