### ISSUE TITLE
Scaling not working on XWayland.

### ISSUE THREAD

**Issue by c-edw** [emoon/rust_minifb#51]
Hi. Currently on an X11 system but I'll try to get more details for you later.

The `minifb::Scale` option appears to have no effect on Wayland. I also seem to remember seeing an info message saying that only `minifb::Scale::X8` and lower is supported. The window starts extremely small.

I believe the system I had the issue on was running Fedora 27, which uses XWayland.

**Comment by c-edw** [comment]
I'm testing on X11 and managed to get out:
`Scale above 4 not support currently, defaults to 4`

**Comment by emoon** [comment]
Hi,

If you set scaling to 4 do you still see no effect?

**Comment by c-edw** [comment]
@emoon There's a difference between 2 and 4. Those work fine. As the info message suggests, scale factors above 4 don't work/are not supported. Can we do anything about this?

**Comment by emoon** [comment]
Yeah so the problem is that X11 doesn't have any support for scaling by itself which macOS and Windows has so I implemented them manually like this

https://github.com/emoon/rust_minifb/blob/master/src/native/x11/X11MiniFB.c#L490

It would easy to implement `x8` or more here. I have manually unrolled it to keep it as fast as possible but the best option would likely to use SIMD here to have good performance.

An other alternative would be to have optional support for OpenGL and have the GPU do that work but I haven't looked into that.

**Comment by emoon** [comment]
I have fixed this now. I will release a new version shortly

**Comment by c-edw** [comment]
@emoon Just gave this a try, X8 seems to be working, but X16 and X32 are still unsupported. Any plans for this in the future?

**Comment by c-edw** [comment]
I would quite like to use X16, as I'm building a CHIP8 emulator which has a 64x32 resolution. Thus, my window is currently only 512x256. I could probably alter my emulator to duplicate a value to do some scaling myself but it would be nice to have in `minifb`. Please do if you have the time, thank you :+1:

**Comment by emoon** [comment]
Alright. I will try to get it sorted during the weekend :)

**Comment by c-edw** [comment]
@emoon I've just noticed some performance differences between scale factors. You said that you were having to implement this scaling manually as X11 doesn't support it, so I assume this what's causing it. Is it possible to optimise this function is anyway? Maybe a `memcpy`? Thanks.

**Comment by emoon** [comment]
The problem is that you can't do a `memcpy` because you need to "expand" a single pixel to multiple pixels so it means that you need to write it to the same buffer several times. Like this

**Comment by emoon** [comment]
I have investigated this now. For `x8` the compiler generates this code

**Comment by emoon** [comment]
I have added x16 and x32 now in `0.10.6` (x32 doesn't seem to behave correct for me but you can try it out, x16 works fine)

**Comment by c-edw** [comment]
They work brilliantly, thank you very much for your hard work :+1:. As for the performance issue, I'm not really sure what the problem is. I am confident that it's due to scaling, as the difference in render speed between X2 and X16 is significant. As you say, I don't think there's much that can be done there though. It's just a little hobby project anyway, performance isn't a big issue. Thanks again!

**Comment by emoon** [comment]
Cool np :) Yeah. As I do the scaling on the CPU there is not much to do to get it faster in higher res this is really a task for the GPU but (like I wrote above) I would need to depend on HW OpenGL acceleration which may or may not be present in the system.
