### ISSUE TITLE
`Scale::FitScreen` produces a window that's too big

### ISSUE THREAD

**Issue by FreeFull** [emoon/rust_minifb#52]
I'm using minifb version 0.10.4, on Linux (x11 backend). My screen resolution is 1366x768. With `Scale::FitScreen` and a 256x256 framebuffer size, the window ends up bigger vertically than my screen.
The following code reproduces the issue:

```rust
extern crate minifb;

use minifb::{Scale, Window, WindowOptions};

fn main() {
    let options = WindowOptions {
        scale: Scale::FitScreen,
        ..Default::default()
    };
    let mut window = Window::new("bug", 256, 256, options).unwrap();
    while window.is_open() {
        window.update();
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}
```

**Comment by emoon** [comment]
Thank. I will take a look at the code in the weekend.

**Comment by emoon** [comment]
I have fixed this now. I will release a new version shortly
