### ISSUE TITLE
Support for raw inputs

### ISSUE THREAD

**Issue by Hammster** [emoon/rust_minifb#54]
Some applications i have require a handling for raw input data, for example when any type of HID is used or inputs affect the non-focused window. 

On windows this would be handled by the `WM_INPUT` messages, but i have no clue about the others.

**Comment by emoon** [comment]
Hi,

Unfortunately I think that is out of the scope for this crate but I would accept a PR for this but that would be needed for all platforms then.

**Comment by Hammster** [comment]
I can give it a try, i'll probably can abstract the how from from this crate, https://github.com/obv-mikhail/InputBot

**Comment by emoon** [comment]
As there hasn't been any progress on this for a long time I will close the issue.
