### ISSUE TITLE
Issues with tiling window manager.

### ISSUE THREAD

**Issue by c-edw** [emoon/rust_minifb#59]
Hey, I'm trying to run an old project using `minifb`. I'm having issues due to using a tiling window manager. I believe the window manager forces the window to be a specific size which the input buffer is too small to fill. 

Sometimes the program will segfault, and other sometimes it will panic with 
```
thread 'main' panicked at 'Failed to update window buffer.: UpdateFailed("Update failed because input buffer is too small. Required size for 1916 x 525 window (1x scale) is 4023600 bytes but the size of the input buffer has the size 1310
2 bytes")', libcore/result.rs:1009:5
```

Thanks.

**Comment by emoon** [comment]
hum.. if the window manager can force the window to a large size the buffer that is being sent int to minifb has to be large enough. Otherwise it may be possible to make sure to set that the window can't be resized when you create the window. 

I'm not sure if the window manager will force it larger anyway and then the only way is really is to make sure to have large enough buffer that minifb will never read outside it

**Comment by c-edw** [comment]
I have defined the window size to be 256x128, but as you can see from the panic message, the window is 1916x525. Is it possible to somehow fit the input buffer to the larger window and fill in the blanks?

**Comment by emoon** [comment]
There is no automatic way to do it currently. I think this is really an issue only on linux where there is no API for doing drawing rescaling to a windows so I have to do the code for scaling myself. Do you know if you set the scale flag of the window to true or false?

**Comment by emoon** [comment]
I tried this on Linux now with i3 (also tiling manager) using `resize: false` for the `WindowOptions` works there at least

**Comment by c-edw** [comment]
Hey, I just tried setting `resize: false` in the WindowOptions and I still get a mix of `input buffer to small` and segfaults. I'm using Sway which might have something to do with it. If it works on i3, it *should* work on Sway...

Thanks for looking into this for me :+1:

**Comment by emoon** [comment]
It seems that Sway doesn't fully check the flags of the window then perhaps? At least in i3 I get a floating windows with the correct size that I have given it so I'm not sure what to do here.

**Comment by c-edw** [comment]
It's probably an issue with Sway. I'll reference this issue and hopefully it can be fixed.

**Comment by emoon** [comment]
Alright. Sounds good :)
