### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by emersion** [emoon/rust_minifb#73]
`unix` assumes X11. Would be nice to have Wayland support too.

**Comment by emoon** [comment]
Yeah that would be nice to add. Currently I don't have time to do it but can perhaps look into it in a month or so. How is Rust support (crates and such) for wayland in general?

**Comment by emersion** [comment]
[wayland-rs](https://github.com/Smithay/wayland-rs) seems to be pretty good

**Comment by tirz** [comment]
[vulkano](https://github.com/vulkano-rs/vulkano) seems to be more popular.
And what about [wgpu-rs](https://github.com/gfx-rs/wgpu-rs)?

**Comment by emoon** [comment]
Those crates has nothing to do with wayland

**Comment by tirz** [comment]
Damn, I totally misread the thread... I think I am tired.
Sorry.

**Comment by nifker** [comment]
Are there currently API changes planned? Because Id like to restructure the code a bit to prepare for Wayland support.

**Comment by emoon** [comment]
No API changes are planned right now.

**Comment by nifker** [comment]
As I started writing a bit code for Wayland I wondered why minifb uses 0RGB and not ARGB - do some platforms not support the alpha channel?

**Comment by emoon** [comment]
What you are showing in minifb is the "final result" so what would would the alpha channel be blended against?

**Comment by nifker** [comment]
Against the colors which are behind the window as most transparent windows do it but I think this should only be the case when the window is borderless.

**Comment by emoon** [comment]
I guess it can be implemented but should be off by default then. I also have no idea if all OSes support this.

**Comment by nifker** [comment]
Created issue #133 for that.

**Comment by nifker** [comment]
How is this to be interpreted?
https://docs.rs/minifb/0.14.0/minifb/struct.WindowOptions.html#structfield.resize
Does true mean resizing is allowed and false resizing is disallowed?
Because the default is false but I am able to resize on X11.

**Comment by emoon** [comment]
That is correct. The "problem" on X11 is that it's just a hint and the OS can ignore it. What otherwise happens (on macOS and Windows) is when you hover the mouse over the lower right corner is that you can't drag and resize the window (or press some button in the window bar)

**Comment by nifker** [comment]
Ok so far I got some stuff now. I mainly need to handle all input and window events now.

**Comment by emoon** [comment]
cool!

**Comment by nifker** [comment]
What should update_with_buffer do when the width and height are unequal to the windows size? Resize the window?

**Comment by emoon** [comment]
I *think* the scaling code will handle that the buffer is too big but I haven't tested. Resizing will not work in some cases (like i3 for example may refuse the resize)

**Comment by nifker** [comment]
Would be nice if people could test my code at this point(and maybe review the code), if there are any issues you can find.

**Comment by cole-h** [comment]
It would make it easier to review/comment on/etc. if it were an actual PR to this repo :wink:. Good work so far!

**Comment by nifker** [comment]
@cole-h Just created it. https://github.com/emoon/rust_minifb/pull/141

**Comment by cole-h** [comment]
I saw, thank you! I'm not the most knowledgeable about Rust or Wayland, but I'll try to make some time to chime in this weekend.

**Comment by nifker** [comment]
@emoon You better close this one.
