### ISSUE TITLE
Why multiple updates are required?

### ISSUE THREAD

**Issue by amarao** [emoon/rust_minifb#74]
I'm very new for this library, and I'm trying to use it for minimal case of 'show one picture and nothing else'.

I decided to get rid of `while` loop and found that `window.update_with_buffer` stop working. After some tinkering I found I need to update screen at least 31 (!!!) times to see result.

My code:
```
extern crate minifb;

use minifb::{Key, WindowOptions, Window};

const WIDTH: usize = 640;
const HEIGHT: usize = 360;

fn main() {
    let  buffer: Vec<u32> = vec![0x77777777; WIDTH * HEIGHT];

    let mut window = Window::new("Test - ESC to exit",
                                 WIDTH,
                                 HEIGHT,
                                 WindowOptions::default()).unwrap_or_else(|e| {
        panic!("{}", e);
    });
      for _ in 0..30 {
            window.update_with_buffer(&buffer).unwrap();
        }
    loop{};
}
```
If I use 30 here, it show black screen, if I use larger values (f.e. 31, 300, etc) - it show expected gray window.

I'm not sure if this is a bug or I do something strange... Is there a way to 'show picture and go idle'?

**Comment by emoon** [comment]
You always need to call `update_with_buffer()` or `update()` this is because update will also read keyboard state, mouse, etc as well.

It might be possible to only call `update_with_buffer()` once and then call `update()` for the remaining calls but that isn't something I have tested.

**Comment by amarao** [comment]
Are there any way to wait for next event, without consuming 100% cpu on update loop?

**Comment by emoon** [comment]
You can add a `std::thread::sleep(..) for 1 ms` in the code in the main loop. You can also limit the update rate this way be checking how long time `update()` took and sleep for the remaining time (so if your update rate is targeting 60 fps (16.667... ms) you can messure the time around the update and subtract that time from 16.6 ms and sleep the rest.

**Comment by amarao** [comment]
Thank you very much for feedback.

I've tried to use plain update with sleep in a loop, and found that I  need to add about 150ms delay before  update_from_buffer give me the picture.

The code is here: https://gist.github.com/amarao/57265c4d7cef413b3b666963c37de061

If I do 30ms sleep before update_with_buffer, there is about 90% chance of get black screen. If I use 50ms, it's about 60%, with 100% - about 20%, with 150ms I get picture all the time.

Is this a bug, or I miss something?

**Comment by emoon** [comment]
The way minifb works is that it uses APIs for each platform to update the window. Exactly how this is implement for each platform is hard to know as it's different. 

For example on macOS I use Metal and there it will need more then one update for something to show up because the data is double buffered to give better performance.

minifb isn't really designed for showing one thing and then don't show it again, it's made for refreshing the buffer all the time (or no buffer at all) so I would expect there might be some issues doing it this way.

**Comment by emoon** [comment]
Do you need some more assistance with this or can this be closed?

**Comment by amarao** [comment]
Yes, I settled on 150ms delay before sending a single update. My petit project is here: https://github.com/amarao/rust_may_2019.

Thank you very much for help!
