### ISSUE TITLE
Panic in Noise Example on Linux (Manjaro x64)

### ISSUE THREAD

**Issue by AHeavner** [emoon/rust_minifb#76]
It looks like in the noise example, sometimes the scale factor causes the example to attempt to open a window wider than the display. It causes an underflow on this line:
`let x = (d.screen_width - width) / 2;`

In my case, width = 5120 and d.screen_width = 2560. Here's the error:

`    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/noise`
thread 'main' panicked at 'attempt to subtract with overflow', src/os/unix/mod.rs:277:21`

**Comment by AHeavner** [comment]
I'd submit a fix but I'm not really sure where'd you'd prefer to fix it. Perhaps the best option would be to assess some of the logic for calculating the scale factor.

**Comment by emoon** [comment]
I'm looking into this now

**Comment by emoon** [comment]
0.12 has now been released and noise example should work fine again
