### ISSUE TITLE
Windows: OBS can't capture minifb windows at other scales than 100%

### ISSUE THREAD

**Issue by hrydgard** [emoon/rust_minifb#84]
There's something wrong with either minifb's or OBS' DPI handling. If you have scaling set to anything other than 100%, OBS window capture captures a lot of black area around the window and scales things wrong.

This could of course also be a bug in OBS. Should probably report to them too.

(OBS: https://obsproject.com ).

**Comment by emoon** [comment]
Alright. It might be an issue in minifb as it's untested for other DPIs than 100%

**Comment by emoon** [comment]
i looked at this today and it seems like the minifb windows gets scaled up correctly while OBS doesn't seem to understand it. A workaround in OBS is to to right click on the window capture (in view) and add cropping on the sides.

**Comment by emoon** [comment]
I wonder if you have looked more into this? From what I can see minifb is behaving correct

**Comment by hrydgard** [comment]
Yeah sorry I haven't had time. I'll make a little repro and report it to OBS soon.

**Comment by emoon** [comment]
Alright. np!

**Comment by emoon** [comment]
Closing for now
