### ISSUE TITLE
Android / iOS support

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#85]
Are there any plans to support android and or ios in the near future?

**Comment by emoon** [comment]
I don't have any plans for it no. I would guess porting the macOS version to iOS wouldn't be that much work except there is really no support for touch in there. For Android I haven't no expertise with so I can't say there.

**Comment by FloVanGH** [comment]
Maybe I will use minifb for the UI-Toolkit OrbTk. There I need also android and ios support. When I'm ready I could try to write a android and ios port for minifb.

**Comment by FloVanGH** [comment]
I'm don't find the time to do a port of minifb for android or iOS. But it is still important for OrbTk. If someone could do it, I would be really happy.

**Comment by ARez2** [comment]
Have their been any updates on this? When i try to install minifb using Termux on my android i get this:

`error occurred: Failed to find tool. Is aarch64-linux-android-ar installed?`

**Comment by emoon** [comment]
I think OrbTK has moved away from minifb (?) and I have no plans of adding this myself so I'm closing the issue for now.
