### ISSUE TITLE
Specify encoding of RGBA colorspace in documentation

### ISSUE THREAD

**Issue by ArifRoktim** [emoon/rust_minifb#88]
The `update_with_buffer` method of `Window` takes a `&[u32]`. That's a byte each for red, green. blue, and alpha. But the specific encoding of the pixel isn't specified in the [docs](https://docs.rs/minifb/0.13.0/minifb/struct.Window.html#method.update_with_buffer). It took a little trial and error to find that the correct encoding for me on Unix is ARGB:

```rust
fn from_u8_rgba(r: u8, g: u8, b: u8, a: u8) -> u32 {
    let (r, g, b, a) = (r as u32, g as u32, b as u32, a as u32);
    b | (g << 8) | (r << 16) | (a << 24)
}
```
```rust
// Color the window magenta
let buffer: Vec<u32> = vec![from_u8_rgba(255, 0, 255, 255); 640 * 400];
let mut window = Window::new("Test", 640, 400, WindowOptions::default()).unwrap();
window.update_with_buffer(&buffer).unwrap();
```

I could make a pull request to add to the docs that the encoding is ARGB but I'm not sure if this is platform specific or not.

**Comment by emoon** [comment]
Yeah please make a PR. That would be great and yes, the encoding is 0RGB on all platforms (upper 8-bits are ignored)

**Comment by chubei-oppen** [comment]
@emoon Does byte order matter here?

**Comment by emoon** [comment]
Yes, it does. The library is designed so you should write `u32` values `(ARGB)` and that should always work. Now if you want to write bytes instead then you need to consider endian-order. That being said a vast majority of arch (for better or worse) is little endian these days so usually one doesn't have to care about it.

**Comment by chubei-oppen** [comment]
Just to be absolutely sure, the `upper 8-bits` in the [documentation](https://docs.rs/minifb/latest/minifb/struct.Window.html#method.update_with_buffer) means the most significant byte, right?

**Comment by emoon** [comment]
Correct

**Comment by benpye** [comment]
It would be nice if this could support other pixel orders to avoid needing to reorder the bytes in code. I realise for some platforms this may still result in swizzling but for example on macOS the format of the texture could be simply changed.
