### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#90]
If I resize the window the frame buffer is not drawn correctly. After resize the pixels are shifted. If I draw the buffer to an png it looks correct. I've read in the documentation there is an issue with resize and u32 buffers.

What could I do to fix this behavior?

**Comment by emoon** [comment]
Hum. I will need to investigate this. I will try to do it when I get home from work today.

**Comment by FloVanGH** [comment]
Thank you.

**Comment by emoon** [comment]
Btw which platform is this on?

**Comment by FloVanGH** [comment]
macOS.

This is the result after resizing:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/6715107/65881882-64f5b500-e394-11e9-85b1-cb33bf91b3fc.png">

**Comment by FloVanGH** [comment]
The code: https://gitlab.redox-os.org/redox-os/orbtk/blob/96-list/crates/shell/src/minifb/mod.rs

**Comment by emoon** [comment]
Alright. Will take a look

**Comment by emoon** [comment]
I think I have found the issue but I haven't solved it yet (in order to achieve good performance I create N number of textures in Metal API that I use to upload the rendered content to the GPU. This is faster than using other APIs. When the resize happen I currently do update the size of the texture which causes things to look bad. I will likely need to re-create the textures but I'm trying to figure out a way that doesn't cause glitches when things gets reized)

**Comment by FloVanGH** [comment]
Ok thank you for the update. Let me known as soon as it is ready, please.

**Comment by emoon** [comment]
Hey, can you try with the version that is in git now? Notice the implementation isn't finished yet so please don't start using it "for real" yet but I just wanted to see if it resolves your issue.

**Comment by FloVanGH** [comment]
Hey, looks much better. After resize is finished (after mouse up) it looks correct.

![Resize](https://user-images.githubusercontent.com/6715107/65993988-a5d3f380-e492-11e9-9d0e-e2408f3bb98c.gif)

**Comment by emoon** [comment]
Alight. Thanks for testing. I will try fix it so it doesn't glitch like that also and yes currently it will scale whats in the image and then "resize" everything once the mouse button in released. I will try to get a more proper implementation done this week

**Comment by FloVanGH** [comment]
Thank you!

**Comment by emoon** [comment]
Sorry I haven't been able to look into this yet. My plan is to make sure it resizes correctly and looks good (and doesn't do the extra scale it does today) I have an idea of how to implement but just haven't got around to do it yet

**Comment by FloVanGH** [comment]
It's ok. Thank you for the update.

**Comment by FloVanGH** [comment]
Some users of OrbTk also reported a panic after resizing the window on Gnome desktop:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpdateFailed("Update failed because input buffer is too small. Required size for 575 x 788 window (1x scale) is 1812400 bytes but the size of the input buffer has the size 1404288 bytes")', src/libcore/result.rs:1084:5
```

**Comment by emoon** [comment]
I see. My plan is to dedicate next week to look at minifb issues and this should be sorted out then.

**Comment by emoon** [comment]
Related to https://github.com/emoon/rust_minifb/issues/105

**Comment by emoon** [comment]
I'm not sure if you have the possibility of test this on on Linux/x11 but I have done a bunch of work on minifb there an the `dev` branch. If you can't test it that is fine as I will start with macOS quite soon after the fixes I have done on Linux.

**Comment by emoon** [comment]
Big batch of `macOS` fixes in the `dev` branch. If you have the possibility to try it out that would be cool.

Also in your case you may want to use something like this for your WindowOptions

```Rust
        WindowOptions {
            resize: true,
            scale_mode: ScaleMode::Center,
            ..WindowOptions::default()
        },
```
or
```Rust
        WindowOptions {
            resize: true,
            scale_mode: ScaleMode::UpperLeft,
            ..WindowOptions::default()
        },
```

Notice that you can now also call `set_background_color(red,green,blue);` (range, 0-255 for each component)

To set the color minifb will use for clearing of the new space. Currently it doesn't work to resize and update the buffer at the same time. I'm not sure why but I don't get any call out to my maincode anymore and macOS just stay inside "render Metal and resize" when one resizes the screen.

It is likely possible to solve this but I'm not sure how.

Also when using `UpperLeft` the rendered buffer "wobbles" a bit. This is something also that would be nice to fix. I looked a bit at it but haven't really figured out why it does so. Regardless it should be nicer when these changes and there is no "distort" after resize anymore.

**Comment by FloVanGH** [comment]
It is much more better. Except those things you have already described. But the background is not set correct. With (r = 59 g = 67 b = 75) I've got a light blue but it should be an dark gray.

**Comment by emoon** [comment]
Doh! bg color fixed in latest commit.

**Comment by FloVanGH** [comment]
Worked. Thank you.

**Comment by FloVanGH** [comment]
This is not yet implemented for windows right? I have there build errors 
```
 277 |         self.0.update_with_buffer_stride(buffer, width, height, width)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `update_with_buffer`
```

**Comment by emoon** [comment]
I have implemented Linux and now macOS. Windows is next on the list

**Comment by emoon** [comment]
Pushed a bunch of windows changes to `dev` Not everything is there yet tho.

**Comment by emoon** [comment]
Closing this one for now as 0.15 has been released. There are still some minor issues (such as glitches) with resizing but overall it should work fine
