### ISSUE TITLE
Is this compatible with imgui?

### ISSUE THREAD

**Issue by NullSense** [emoon/rust_minifb#91]
Is rust_minifb compatible with [imgui-rs](https://github.com/Gekkio/imgui-rs)?

**Comment by emoon** [comment]
if there is a software renderer for `imgui-rs` it would work. While `rust_minifb` uses GPU in some cases to display the buffer supplied by the user the GPU isn't exposed.

**Comment by emoon** [comment]
Closing this as it will be tracked in #93

**Comment by emoon** [comment]
Closing this as it will be tracked in #93
